# Generated by Django 3.2.6 on 2021-08-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='done_fortoday',
        ),
        migrations.AddField(
            model_name='habit',
            name='done_for_today',
            field=models.BooleanField(default=False),
        ),
    ]
